name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages-tests
      url: https://tadeu-dutra.github.io/string-search-app/lcov-report/index.html
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   path: string-search-app

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # cache: 'npm'
          # cache-dependency-path: string-search-app/package.json

      - name: Install dependencies
        run: npm install
        # working-directory: string-search-app/lcov-report

      - name: Test and Generate Coverage
        run: npm run test:coverage
        env:
          NODE_ENV: development
        # working-directory: string-search-app/lcov-report

      # - name: Prepare Coverage Report
      #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
      #   run: |
      #     echo "<!DOCTYPE html><html><body><h1>Coverage Report</h1><p><a href=\"lcov-report/index.html\">View Coverage</a></p></body></html>" > string-search-app/coverage/index.html
      #   # working-directory: .

      # - name: Inspect Coverage Directory
      #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
      #   # run: ls -la string-search-app/coverage/
      #   run: ls -la string-search-app/lcov-report
      #   # working-directory: .

      - name: Upload Coverage Report Artifact
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
        uses: actions/upload-pages-artifact@v3
        env:
          NODE_ENV: development
        with:
          path: coverage/
          overwrite: true

      - name: Deploy to GitHub Pages
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
        uses: actions/deploy-pages@v4
        env:
          NODE_ENV: development
        with:
          path: coverage/
          overwrite: true




  # deploy:
  #   runs-on: ubuntu-latest
  #   if: always()
  #   needs: test
  #   permissions:
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages-app
  #     url: https://tadeu-dutra.github.io/string-search-app/
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         path: string-search-app

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18'
  #         cache: 'npm'
  #         cache-dependency-path: string-search-app/package.json

  #     - name: Install dependencies
  #       run: npm install
  #       working-directory: string-search-app

  #     - name: Build Web Application
  #       if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
  #       run: |
  #         npm run build -- --display-error-details || { echo "Build failed"; exit 1; }
  #         echo "Build output:"
  #         ls -la string-search-app/dist/ || echo "dist/ directory not found after build"
  #         if [ -f string-search-app/dist/index.html ]; then
  #           echo "index.html contents:"
  #           cat string-search-app/dist/index.html
  #         else
  #           echo "index.html not found in dist/"
  #         fi
  #       working-directory: string-search-app

  #     - name: Prepare Web Application
  #       if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
  #       run: |
  #         mkdir -p string-search-app/public
  #         if [ -d "string-search-app/dist/" ]; then
  #           cp -r string-search-app/dist/* string-search-app/public/
  #           if [ -f string-search-app/dist/index.html ]; then
  #             cp string-search-app/dist/index.html string-search-app/public/index.html
  #           else
  #             echo "index.html not found in dist/, creating placeholder"
  #             echo "<html><body><h1>Application Not Built Correctly</h1></body></html>" > string-search-app/public/index.html
  #           fi
  #         else
  #           echo "dist/ not found, skipping copy"
  #           echo "<html><body><h1>Build Failed</h1></body></html>" > string-search-app/public/index.html
  #         fi
  #         ls -la string-search-app/public/ || echo "public/ directory empty or not created"
  #       working-directory: .

  #     - name: Inspect Public Directory
  #       if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
  #       run: ls -la string-search-app/public/
  #       working-directory: .

  #     - name: Upload Pages Artifact
  #       if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
  #       uses: actions/upload-pages-artifact@v3
  #       with:
  #         path: string-search-app/public/

  #     - name: Deploy to GitHub Pages
  #       if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
  #       uses: actions/deploy-pages@v4


  deploy:
    runs-on: ubuntu-latest
    if: always()
    needs: test
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages-app
      url: https://tadeu-dutra.github.io/string-search-app/index.html
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   path: .

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          overwrite: true
          # cache: 'npm'
          # cache-dependency-path: package.json

      - name: Install dependencies
        run: npm install
        # working-directory: .

      - name: Build Web Application
        run: |
          npm run build || { echo "Build failed"; exit 1; }
          ls -la dist/ || echo "dist/ directory not found after build"
        env:
          NODE_ENV: production
          overwrite: true
        # working-directory: .
      
      # - name: Upload pages artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: dist/
      #     overwrite: true
      
      - name: Deploy to GitHub Pages
        # if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
        uses: actions/deploy-pages@v4
        env:
          NODE_ENV: production
        with:
          path: dist/
          overwrite: true







# ]

#   deploy:
#     runs-on: ubuntu-latest
#     if: always()
#     needs: test
#     permissions:
#       pages: write
#       id-token: write
#     environment:
#       name: github-pages-app
#       url: https://tadeu-dutra.github.io/string-search-app/index.htnl
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           path: .

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '18'
#           cache: 'npm'
#           cache-dependency-path: package.json

#       - name: Install dependencies
#         run: npm install
#         working-directory: .

#       - name: Build Web Application
#         run: npm run build
        
#         # if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
#         # run: |
#         #   npm run build || { echo "Build failed"; exit 1; }
#         #   ls -la dist/ || echo "dist/ directory not found after build"
#         # working-directory: .

#       # - name: Download Coverage Artifact
#       #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
#       #   uses: actions/download-artifact@v4
#       #   with:
#       #     name: github-pages-artifact-test  # Default name for upload-pages-artifact
#       #     path: coverage/

#       # - name: Prepare Web Application and Coverage
#       #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
#       #   run: |
#       #     mkdir -p public
#       #     if [ -d "dist/" ]; then cp -r dist/* public/; else echo "dist/ not found, skipping copy"; fi
#       #   working-directory: .

#       # - name: Prepare Coverage Report
#       #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
#       #   run: |
#       #     cp coverage/lcov-report/index.html public/coverage/index.html
#       #     echo "<!DOCTYPE html><html><body><h1>Coverage Report</h1><p><a href=\"coverage/lcov-report/index.html\">View Coverage</a></p></body></html>" > public/coverage/index.html
#       #   working-directory: .

#       # - name: Upload Pages Artifact
#       #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
#       #   uses: actions/upload-pages-artifact@v3
#       #   with:
#       #     path: public/

#       - name: Deploy to GitHub Pages
#         if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
#         uses: actions/deploy-pages@v4
#         with:
#           path: dist/