name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://tadeu-dutra.github.io/string-search-app/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install -U

      - name: Run tests and generate coverage
        run: npm run test:coverage

      - name: Build web application
        run: npm run build

      - name: Prepare coverage report artifact
        run: |
          mkdir -p public/coverage
          cp -r coverage/* public/coverage/

      - name: Prepare web application artifact
        run: |
          mkdir -p public/dist
          cp -r dist/* public/dist/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4