name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://tadeu-dutra.github.io/string-search-app/lcov-report/index.html
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Test and Generate Coverage
        run: npm run test:coverage

      # - name: Prepare Web Application Build
      #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
      #   run: |
      #     npm run build
      #     cp -r coverage/ dist/coverage/ || echo "No coverage to copy"
      #     cp coverage/index.html dist/coverage/index.html || echo "No coverage index to copy"

      # - name: Upload Web Application Artifact
      #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: dist/

      - name: Prepare Coverage Report
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
        run: |
          cp coverage/lcov-report/index.html coverage/index.html
          echo "<!DOCTYPE html><html><body><h1>Coverage Report</h1><p><a href=\"lcov-report/index.html\">View Coverage</a></p></body></html>" > coverage/index.html

      - name: Upload Coverage Report Artifact
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
        uses: actions/upload-pages-artifact@v3
        with:
          path: coverage/

      # - name: Deploy to GitHub Pages
      #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
      #   uses: actions/deploy-pages@v4

  # deploy:
  #   name: Deploy to GitHub Pages
  #   runs-on: ubuntu-latest
  #   if: always()
  #   needs:
  #     - ci_pipeline
  #   permissions:
  #     contents: read
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: https://tadeu-dutra.github.io/string-search-app/lcov-report/index.html
  #   steps:
  #     # - name: Deploy to GitHub Pages
  #     #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
  #     #   uses: actions/deploy-pages@v4

  #     - name: Upload Coverage Report Artifact
  #       if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
  #       uses: actions/upload-pages-artifact@v3
  #       with:
  #         path: coverage/